CREATE DATABASE Banking_System; -- Created Database
USE Banking_System; -- Accessed the Database

CREATE TABLE CUSTOMERS(
CUSTOMERID INT,
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
EMAIL VARCHAR(100),
PHONE VARCHAR(10));

DESCRIBE TABLE CUSTOMERS;
DESCRIBE CUSTOMER;
SELECT *
 FROM CUSTOMERS; -- viewing all rows and columns of table customers

ALTER TABLE CUSTOMERS
ADD COLUMN ACCOUNTCREATIONDATE DATE;

CREATE TABLE ACCOUNTS(
ACCOUNTID INT,
ACCOUNTTYPE VARCHAR(20),
BALANCE DECIMAL(10,2));

CREATE TABLE TRANSACTIONS(
TRANSACTIONID INT,
TRANSACTIONDATE DATE, 
AMOUNT DECIMAL(10,2),
TRANSACTIONTYPE VARCHAR(20));

CREATE TABLE BRANCHES(
BRANCHID INT,
BRANCHNAME VARCHAR(100),
BRANCHADDRESS VARCHAR(255),
BRANCHPHONE VARCHAR(20));

CREATE TABLE ACCOUNTSBRANCHES(
ASSIGNEDDATE DATE);

CREATE TABLE LOANS(
LOANID INT,
LOANAMOUNT DECIMAL(10,2),
INTERESTRATE DECIMAL(5,2),
STARTDATE DATE,
ENDDATE DATE);

SHOW TABLES;
ALTER TABLE CUSTOMERS
DROP COLUMN ACCOUNTCREATIONDATE;

SELECT *
FROM  CUSTOMERS;

ALTER TABLE CUSTOMERS
ADD COLUMN BIRTHDATE DATE;

ALTER TABLE CUSTOMERS
MODIFY PHONE VARCHAR(20),
ADD PRIMARY KEY (CUSTOMERID);

DESCRIBE CUSTOMERS;

DROP TABLE ACCOUNTSBRANCHES;

SELECT *
FROM ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD CUSTOMERID INT;

ALTER TABLE ACCOUNTS
ADD CONSTRAINT
foreign key (CUSTOMERID)
references CUSTOMERS(CUSTOMERID);


ALTER TABLE TRANSACTIONS
ADD ACCOUNTID INT;

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT
FOREIGN KEY (ACCOUNTID)
REFERENCES ACCOUNTS(ACCOUNTID);

DESCRIBE ACCOUNTS;

ALTER TABLE ACCOUNTS
ADD PRIMARY KEY (ACCOUNTID);

ALTER TABLE TRANSACTIONS
ADD CONSTRAINT
FOREIGN KEY (ACCOUNTID)
REFERENCES ACCOUNTS(ACCOUNTID);

DESCRIBE TRANSACTIONS;

ALTER TABLE TRANSACTIONS
ADD PRIMARY KEY (TRANSACTIONID);

ALTER TABLE BRANCHES
ADD PRIMARY KEY (BRANCHID);
DESCRIBE BRANCHES;

ALTER TABLE LOANS
ADD PRIMARY KEY (LOANID),
ADD CUSTOMERID INT,
ADD CONSTRAINT
FOREIGN KEY (CUSTOMERID)
REFERENCES CUSTOMERS(CUSTOMERID);

DESCRIBE TRANSACTIONS;

ALTER TABLE ACCOUNTS
ADD BRANCHID INT,
ADD CONSTRAINT
FOREIGN KEY (BRANCHID)
REFERENCES BRANCHES(BRANCHID);

ALTER TABLE CUSTOMERS
MODIFY FIRSTNAME VARCHAR(50) NOT NULL,
MODIFY EMAIL VARCHAR(100) UNIQUE;

DESCRIBE CUSTOMERS;

-- ADDING RECORDS INSIDE THE TABLE

INSERT INTO CUSTOMERS VALUES 
(101,'Rahul','Sharma','Rahul.sharma@gmail.com','9767983712','1995-04-12');

SELECT *
FROM CUSTOMERS;

INSERT INTO CUSTOMERS VALUE
(102,'Samyak','Ubale','Samyakubale1@gmail.com','7249727616','2004-03-20'),
(103,'Suraj','Thange','Surajthange65@gmail.com',null,'2004-02-10'),
(104,'Jitesh','Bhoir','Jiteshbhoir34@gmail.com','8945762457','2002-04-24'),
(105,'Ajit','Pashte', 'Ajitpashte44@gmail,com','7845795612','2004-02-15');

INSERT INTO BRANCHES (BRANCHID,BRANCHNAME,BRANCHADDRESS,BRANCHPHONE)
VALUES
(1,'Mumbai Main Branch','Andheri East, Mumbai','0224571554'),
(2,'Pune Central Branch','Shivaji Nagar, Pune','0224568816'),
(3,'Banglore Branch','MG Road, Banglore','0224571988'),
(4,'Delhi Branch','Connaught Palace, Delhi',null),
(5,'Hyderabad Branch',null,'0224571554');

SELECT *
FROM BRANCHES;

SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO ACCOUNTS VALUES
(1001,'Savings','2500000',102,1),
(1002,'Current','45000.50',101,2),
(1003,'Savings','85000.54',102,3),
(1004,'Salary','35500.98',101,4),
(1005,'Savings','56500.86',103,5),
(1006,'Savings','87000.05',105,2),
(1007,'Current','68000.45',104,5),
(1008,'Savings','68256.89',103,3);

SELECT *
FROM ACCOUNTS;

INSERT INTO TRANSACTIONS (TRANSACTIONID,TRANSACTIONDATE,AMOUNT,TRANSACTIONTYPE,ACCOUNTID)
 VALUE
(5001,'2026-01-15',10000,'Deposit',1001),
(5002,'2026-01-25',2500,'Withdrawal',1003),
(5003,'2026-02-12',52000,'Deposit',1004),
(5004,'2026-03-04',3000,'Withdrawal',1005),
(5005,'2026-03-29',7500,'Deposit',1001),
(5006,'2026-03-05',16000,'Deposit',1002),
(5007,'2026-03-15',18000,'Transfer',1003),
(5008,NULL,26000,'Deposit',1002),
(5009,'2026-04-18',10500,'Withdrawal',1005),
(5010,NULL,26000,'Withdrawal',1002),
(5011,'2026-02-22',15000,'Deposit',1003),
(5012,'2026-01-14',16000,'Transfer',1002),
(5013,'2026-02-15',56000,'Deposit',1002),
(5014,'2026-03-04',null,'Withdrawal',1005),
(5015,'2026-03-29',7500,'Deposit',1001);

SELECT *
FROM TRANSACTIONS;

INSERT INTO LOANS(LOANID,LOANAMOUNT,INTERESTRATE,STARTDATE,ENDDATE,CUSTOMERID)
VALUES
(9001,500000,8.50,'2025-01-24','2030-02-15',101),
(9002,20000,9.25,'2025-03-14','2026-02-15',103),
(9003,220000,NULL,'2025-02-22','2035-02-15',105),
(9004,450000,8.50,'2025-011-08','2045-02-15',104),
(9005,110000,7.90,NULL,'2029-02-15',103),
(9006,3500000,9.50,'2025-08-07','2035-02-15',103);

SELECT *
FROM ACCOUNTS;

SELECT *
FROM BRANCHES;

SELECT *
FROM CUSTOMERS;

SELECT *
FROM LOANS;

SELECT * 
FROM TRANSACTIONS;

UPDATE CUSTOMERS
SET PHONE = "879665741"
WHERE CUSTOMERID = 103; -- UPDATED A PHONE NUMBER

DELETE FROM TRANSACTIONS
WHERE TRANSACTIONID = 5008; -- DELETED THE TRANSACTIONID

UPDATE LOANS
SET INTERESTRATE = "10.25"
WHERE LOANID = 9003; -- UPDATED THE INTERESTRATE

UPDATE ACCOUNTS
SET BALANCE = 554500.22
WHERE ACCOUNTID = 1002; -- UPDATED THE BALANCE

UPDATE TRANSACTIONS
SET ACCOUNTID = 1004
WHERE TRANSACTIONID IN (5004,5005);

-- EXTRACTING THE DATA
SELECT FIRSTNAME,EMAIL,CUSTOMERID
FROM CUSTOMERS;

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID = 102; -- CALLING SPECIFIC DATA

SELECT *
FROM CUSTOMERS
WHERE CUSTOMERID = 102 OR CUSTOMERID = 103; -- CALLING MULTIPLE ID's

SELECT * -- CALLING DATA BY BIRTHDATE
FROM CUSTOMERS
WHERE BIRTHDATE >= '1995-01-01' AND BIRTHDATE <= '2002-12-31';


-- CUSTOMER ANALYSIS


-- HOW MANY CUSTOMERS ARE THERE?
SELECT COUNT(*) AS TOTAL_CUSTOMERS -- COLUMN ALISES
FROM CUSTOMERS;

-- WHICH CUSTOMERS HAVE MISSING INFORMATION?
SELECT CUSTOMERID, FIRSTNAME AS NAME
FROM CUSTOMERS
WHERE LASTNAME IS NULL OR EMAIL IS NULL;

-- WHO ARE THE YOUNGEST/OLDEST CUSTOMERS?
SELECT 
MAX(BIRTHDATE) AS YOUNGEST_CUSTOMER,
MIN(BIRTHDATE) AS OLDEST_CUSTOMER
FROM CUSTOMERS;

-- HOW MANY CUSTOMERS WERE BORN BEFORE/AFTER A PARTICULAR YEAR?
-- BEFORE 2000
SELECT *
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) <= 2000;
-- AFTER 2000 
SELECT *
FROM CUSTOMERS
WHERE YEAR(BIRTHDATE) > 2000;

-- WHICH CUSTOMERS HAVE MULTIPLE ACCOUNTS
SELECT CUSTOMERID, COUNT(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY CUSTOMERID
HAVING TOTAL_ACCOUNTS >1;


-- ACCOUNT ANALYSIS


-- HOW MANY SAVINGS, CURRENT AND SALARY ACCOUNTS EXIST?
SELECT ACCOUNTTYPE, COUNT(*) AS TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY ACCOUNTTYPE;

-- WHAT IS THE TOTAL BALANCE?
SELECT SUM(BALANCE) TOTAL_BALANCE
FROM ACCOUNTS;

-- WHAT IS THE AVERAGE BALANCE
SELECT AVG(BALANCE) AVERAGE_BALANCE
FROM ACCOUNTS;

-- WHICH CUSTOMERS HAVE THE HIGHEST BALANCES?
SELECT CUSTOMERID, BALANCE HIGHEST_BALANCE
FROM ACCOUNTS
ORDER BY BALANCE DESC LIMIT 1;

-- WHICH ACCOUNTS HAVE NULL BALANCES?
SELECT *
FROM ACCOUNTS
WHERE BALANCE=NULL;

-- WHICH BRANCH MANAGES THE MOST ACCOUNTS?
SELECT BRANCHID,COUNT(*) TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY TOTAL_ACCOUNTS DESC LIMIT 3;


-- TRANSACTION ANALYSIS


-- WHAT IS THE TOTAL TRANSACTION AMOUNT?
SELECT SUM(AMOUNT) TOTAL_TRANACTION_AMOUNT
FROM TRANSACTIONS;

-- HOW MANY DEPOSITS/WITHDRAWALS/TRANSFERS ARE THERE?
SELECT TRANSACTIONTYPE, COUNT(*) AS TOTAL_TRANSACTIONS
FROM TRANSACTIONS
GROUP BY TRANSACTIONTYPE;

-- WHICH ACCOUNT HAS THE HIGHEST TRANSACTION ACTIVITY?
SELECT ACCOUNTID,COUNT(*) TOTAL_TRANSACTIONS
FROM TRANSACTIONS
GROUP BY ACCOUNTID
ORDER BY TOTAL_TRANSACTIONS DESC LIMIT 1;

-- WHAT IS THE AVERAGE TRANSACTION AMOUNT?
SELECT AVG(AMOUNT) AVERAGE_TRANSACTION_AMOUNT
FROM TRANSACTIONS;

-- WHICH TRANSACTIONS HAVE MISSING DATES/AMOUNTS?
SELECT *
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NULL OR AMOUNT IS NULL;


-- LOAN ANALYSIS


-- WHAT IS TOTAL LOAN AMOUNT?
SELECT  SUM(LOANAMOUNT) TOTAL_LOAN_AMOUNT
FROM LOANS;

-- WHICH CUSTOMER HAS THE LARGEST LOAN?
SELECT * 
FROM LOANS;
SELECT CUSTOMERID, SUM(LOANAMOUNT) TOTAL_LOAN
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY TOTAL_LOAN DESC LIMIT 1;

-- WHICH LOAN HAS THE HIGHEST INTEREST RATE?
SELECT LOANID, MAX(INTERESTRATE) INTREST_RATE
FROM LOANS
GROUP BY LOANID
ORDER BY INTREST_RATE DESC LIMIT 1;

-- WHICH LOANS ARE STILL ACTIVE?
SELECT *
FROM LOANS
WHERE ENDDATE>2026;

-- WHICH CUSTOMERS HAVE MULTIPLE LOANS?
SELECT CUSTOMERID, COUNT(LOANID) LOANS
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY LOANS DESC LIMIT 1;

-- WHAT IS THE AVERAGE LOAN AMOUNT?
SELECT AVG(LOANAMOUNT) AVERAGE_LOAN_AMOUNT
FROM LOANS;


-- BRANCH ANALYSIS


SELECT *
FROM ACCOUNTS;

-- WHICH BRANCH HAS THE MOST CUSTOMERS/ACCOUNTS?
SELECT BRANCHID,COUNT(ACCOUNTID) TOTAL_ACCOUNTS
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY TOTAL_ACCOUNTS DESC LIMIT 1;

-- WHICH BRANCH HAS THE HIGHEST TOTAL ACCOUNT BALANCE?
SELECT BRANCHID, SUM(BALANCE) TOTAL_BALANCE
FROM ACCOUNTS
GROUP BY BRANCHID
ORDER BY TOTAL_BALANCE DESC LIMIT 1;

-- WHICH BRANCH HANDLES THE MOST TRANSACTIONS?
-- Account with Max Transactions
SELECT ACCOUNTID, COUNT(*) Total_Transactions 
FROM TRANSACTIONS
GROUP BY ACCOUNTID 
ORDER BY Total_transactions DESC LIMIT 1;
-- Branch with Max Transactions
SELECT BRANCHID
FROM ACCOUNTS
WHERE ACCOUNTID = 1003;

-- WHICH BRANCH HAS THE HIGHEST LOAN EXPOSURE?
-- Customer with Max Loan Amount
SELECT CUSTOMERID, SUM(LOANAMOUNT) Total_Loan_Amount
FROM LOANS
GROUP BY CUSTOMERID
ORDER BY Total_Loan_Amount DESC LIMIT 1;
-- Branch with Max Loan Amount
SELECT BRANCHID 
FROM ACCOUNTS
WHERE CUSTOMERID = 104;


-- FUNCTIONS


-- STRING FUNCTIONS
SELECT CUSTOMERID, CONCAT(FIRSTNAME," ",LASTNAME) AS FULL_NAME
FROM CUSTOMERS;

-- UPPER 
SELECT CUSTOMERID, UPPER(CONCAT(FIRSTNAME," ",LASTNAME)) AS FULL_NAME
FROM CUSTOMERS;

-- LOWER 
SELECT CUSTOMERID, LOWER(CONCAT(FIRSTNAME," ",LASTNAME)) AS FULL_NAME
FROM CUSTOMERS;

-- LENGTH
SELECT FIRSTNAME, LENGTH(FIRSTNAME) AS NAME_LENGTH
FROM CUSTOMERS
HAVING NAME_LENGTH <= 5
ORDER BY NAME_LENGTH DESC LIMIT 1 OFFSET 1; -- OFFSET IS USED TO SKIP THE VALUE

-- CHAR_LENGTH
SELECT FIRSTNAME, CHAR_LENGTH(FIRSTNAME) AS CHARACTER_LENGTH
FROM CUSTOMERS;

-- LEFT
SELECT FIRSTNAME,LEFT(FIRSTNAME,3)
FROM CUSTOMERS;

-- RIGHT
SELECT PHONE,RIGHT(PHONE,4) AS LAST_4_DIGITS
FROM CUSTOMERS;
SELECT CUSTOMERID,CONCAT("XXXX",RIGHT(PHONE,4)) MASKED_PHONENO
FROM CUSTOMERS;

-- SUBSTRING
SELECT EMAIL,SUBSTRING(EMAIL,1,5) AS EMAIL_PART
FROM CUSTOMERS;

-- SUBSTRING_INDEX
SELECT EMAIL,SUBSTRING_INDEX(EMAIL,"@",-1) AS EMAIL_PART 				-- 1 BEFORE SPECIFIC CHAR, -1 FOR AFTER SPECIFIC CHAR
FROM CUSTOMERS;

-- TRIM
SELECT TRIM("SAMYAK UBALE          ") AS NAME;							-- REMOVES USELESS SPACES

-- REPLACE
SELECT EMAIL,REPLACE(EMAIL,'gmail.com','email.com') AS EMAILS
FROM CUSTOMERS;

-- LOCATE
SELECT EMAIL, LOCATE("@",EMAIL) AS POSITION				-- LOCATE POSITION
FROM CUSTOMERS;


-- MATH FUNCTION


-- ROUND
SELECT ACCOUNTID,BALANCE,ROUND(BALANCE,0)AS ROUNDED_BALANCE				-- ROUNDS OF THE DECIMAL VALUE
FROM ACCOUNTS;

-- CEIL/CEILING
SELECT BALANCE,CEIL(BALANCE) AS ROUNDUP_BALANCE
FROM ACCOUNTS;															 -- ROUNDS UP THE VALUE

-- FLOOR
SELECT BALANCE,FLOOR(BALANCE) AS ROUNDUP_BALANCE
FROM ACCOUNTS;															-- ROUNDS DOWN THE VALUE

-- ABS
SELECT ABS(-6548) AS ABSOLUTE_VALUE;									-- RETURNS ABSOULTE VALUE

-- MOD
SELECT ACCOUNTID,MOD(ACCOUNTID,2) AS REMINDER
FROM ACCOUNTS;															-- RETURNS REMAINING VALUE

-- CASE THEN END IS JUST LIKE IF - ELSE STATEMENT
SELECT ACCOUNTID,MOD(ACCOUNTID,2) AS REMINDER,CASE
WHEN MOD(ACCOUNTID,2)=0 THEN "EVEN"
ELSE "ODD"
END AS ID_TYPE
FROM ACCOUNTS;

-- POWER
SELECT POWER(5,5)
AS RESULT;													-- WORKS LIKE INDICES

-- SQRT
SELECT BALANCE,SQRT(BALANCE) AS SQRT
FROM ACCOUNTS;												-- RETURNS SQUAREROOT

-- GREATEST 
SELECT ACCOUNTID, BALANCE,GREATEST(BALANCE,25000) AS MINIMUM_BALANCE 
FROM ACCOUNTS;													-- COMPARES VALUES

-- LEAST
SELECT ACCOUNTID,BALANCE,LEAST(BALANCE,50000) AS MAX_LIMIT
FROM ACCOUNTS;													-- COMPARES VALUES

-- CALCULATE ANNUAL INTEREST
SELECT LOANID,LOANAMOUNT,INTERESTRATE, ROUND(LOANAMOUNT * INTERESTRATE /100,2) AS ANNUAL_INTEREST
FROM LOANS;

-- LOAN AMOUNT + INTEREST
SELECT LOANID,LOANAMOUNT,INTERESTRATE,
ROUND(LOANAMOUNT+(LOANAMOUNT * INTERESTRATE / 100),2) AS PRINCIPAL_PLUS_ONEYEAR_INTEREST
FROM LOANS;

-- BALANCE CATEGORY
SELECT ACCOUNTID,BALANCE,
CASE
WHEN BALANCE IS NULL THEN "UNKNOWN"
WHEN BALANCE < 10000 THEN"LOW"
WHEN BALANCE < 50000 THEN "MEDIUM"
ELSE "HIGH"
END AS BALANCE_CATEGORY
FROM ACCOUNTS;


-- DATE & TIME FUNCTIONS


SELECT CURDATE() AS TODAY;			-- TODAY'S DATE
SELECT SYSDATE() AS TODAY;			-- TODAY'S DATE WITH TIME
-- YEAR
SELECT CUSTOMERID,BIRTHDATE,YEAR(BIRTHDATE) AS BIRTH_YEAR
FROM CUSTOMERS;
-- MONTH
SELECT CUSTOMERID,BIRTHDATE,MONTH(BIRTHDATE) AS BIRTH_MONTH
FROM CUSTOMERS;
-- MONTHNAME
SELECT CUSTOMERID,BIRTHDATE,MONTHNAME(BIRTHDATE) AS BIRTH_MONTH
FROM CUSTOMERS;
-- DAY
SELECT TRANSACTIONID,TRANSACTIONDATE,DAY(TRANSACTIONDATE) AS DAY_NUMBER
FROM TRANSACTIONS;
-- DAYNAME
SELECT TRANSACTIONID,TRANSACTIONDATE,DAYNAME(TRANSACTIONDATE) AS DAY_NAME
FROM TRANSACTIONS;
-- QUATER 
SELECT TRANSACTIONID,TRANSACTIONDATE,QUARTER(TRANSACTIONDATE) AS DAY_NAME
FROM TRANSACTIONS;
SELECT QUARTER(TRANSACTIONDATE) AS QUARTERS, COUNT(*) AS TRANSACTION_COUNT,
SUM(AMOUNT) AS TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY QUARTER(TRANSACTIONDATE);

-- DATEDIFF
SELECT LOANID,STARTDATE,ENDDATE,DATEDIFF(ENDDATE,STARTDATE) AS LOAN_DAYS
FROM LOANS;

-- CALCULATE LOAN DURATION IN TERMS OF YEAR
SELECT LOANID,STARTDATE,ENDDATE,ROUND(DATEDIFF(ENDDATE,STARTDATE)/365,2) AS LOAN_YEARS
FROM LOANS
WHERE ENDDATE IS NOT NULL;

-- TIMESTAMDIFF
SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AS AGE
FROM CUSTOMERS;

-- AGE GROUP
SELECT CUSTOMERID,FIRSTNAME,BIRTHDATE,TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) AS AGE,
CASE
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) <25 THEN "Young Adult"
WHEN TIMESTAMPDIFF(YEAR,BIRTHDATE,CURDATE()) BETWEEN 25 AND 40 THEN "Adult"
ELSE "Senior Citizen"
END AS AGE_GROUP
FROM CUSTOMERS;

-- DATE_FORMAT
SELECT TRANSACTIONDATE,DATE_FORMAT(TRANSACTIONDATE, '%d-%m-%y') AS FORMATED_DATE
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL;
SELECT TRANSACTIONDATE,DATE_FORMAT(TRANSACTIONDATE, '%M-%Y') AS FORMATED_DATE
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL;

-- MONTHLY TRANSACTIONS
SELECT 
DATE_FORMAT(TRANSACTIONDATE,'%Y-%m') AS MONTH,
COUNT(*) AS TRANSACTION_COUNTS,
SUM(AMOUNT)AS TOTAL_AMOUNT
FROM TRANSACTIONS
WHERE TRANSACTIONDATE IS NOT NULL
GROUP BY DATE_FORMAT(TRANSACTIONDATE,'%Y-%m')
ORDER BY MONTH;

-- LAST 30 DAYS TRANSACTIONS
SELECT *
FROM TRANSACTIONS 
WHERE TRANSACTIONDATE >= DATE_SUB('2026-02-01', INTERVAL 30 DAY);
-- ADDING DAYS TO THE DATE
SELECT TRANSACTIONID,TRANSACTIONDATE,DATE_ADD(TRANSACTIONDATE,INTERVAL 30 DAY) AS AFTER_30_DAYS
FROM TRANSACTIONS;

-- LOAN STATUS USING DAYS
SELECT LOANID, STARTDATE,ENDDATE,
CASE
WHEN ENDDATE IS NULL THEN "NO END DATE"
WHEN ENDDATE <CURDATE() THEN "COMPLETED"
ELSE "ACTIVE"
END AS LOAN_STATUS
FROM LOANS;


-- WINDOWS FUNCTIONS


-- RANK & OVER
SELECT LOANID,LOANAMOUNT,RANK() OVER(ORDER BY LOANAMOUNT DESC) AS LOAN_RANK
FROM LOANS;

SELECT * FROM TRANSACTIONS;
SELECT TRANSACTIONID,AMOUNT,RANK() OVER(ORDER BY AMOUNT DESC) AS TRANSACTION_RANK,
DENSE_RANK() OVER(ORDER BY AMOUNT DESC) AS TRANSACTION_DENSE_RANK								-- DENSE RANK (NEVER SKIPS RANK VALUES)
FROM TRANSACTIONS;

SELECT TRANSACTIONID,TRANSACTIONTYPE,AMOUNT,
DENSE_RANK() OVER(PARTITION BY TRANSACTIONTYPE ORDER BY AMOUNT DESC) AS TRANSACTION_RANK		-- PARTITION BY
FROM TRANSACTIONS;

-- ROW NUMBER
SELECT LOANID,CUSTOMERID,LOANAMOUNT,ROW_NUMBER() OVER(ORDER BY LOANAMOUNT DESC) AS ROWNUMBER
FROM LOANS; 

SELECT LOANID,CUSTOMERID,LOANAMOUNT,
ROW_NUMBER() OVER(PARTITION BY CUSTOMERID ORDER BY LOANAMOUNT DESC) AS ROWNUMBER
FROM LOANS;

-- SUM 
SELECT LOANID,CUSTOMERID,LOANAMOUNT,
SUM(LOANAMOUNT) OVER (ORDER BY LOANAMOUNT DESC) AS RUNNING_TOTAL
FROM LOANS;

SELECT LOANID,CUSTOMERID,LOANAMOUNT,
SUM(LOANAMOUNT) OVER (PARTITION BY CUSTOMERID ORDER BY LOANAMOUNT DESC) AS RUNNING_TOTAL
FROM LOANS;

-- LAG
SELECT LOANID,CUSTOMERID,LOANAMOUNT,
LAG(LOANAMOUNT) OVER(ORDER BY LOANAMOUNT DESC) AS PREVIOUS_LOANAMOUNT
FROM LOANS;

-- LEAD
SELECT LOANID,CUSTOMERID,LOANAMOUNT,
LEAD(LOANAMOUNT) OVER(ORDER BY LOANAMOUNT DESC) AS PREVIOUS_LOANAMOUNT
FROM LOANS;

SELECT LOANID,CUSTOMERID,LOANAMOUNT,
LEAD(LOANAMOUNT) OVER(PARTITION BY CUSTOMERID ORDER BY LOANAMOUNT DESC) AS NEXT_LOANAMOUNT
FROM LOANS;
